return {
  opts = {
    -- https://github.com/nvim-treesitter/nvim-treesitter?tab=readme-ov-file#supported-languages
    ensure_installed = {
      "bash",
      "c",
      "cmake",
      "cpp",
      "css",
      "c_sharp",
      "diff",
      "dockerfile",
      "fish",
      "gdscript",
      "gdshader",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "git_config",
      "git_rebase",
      "glsl",
      "go",
      "groovy",
      "hlsl",
      "html",
      "ini",
      "java",
      "javascript",
      "json",
      "lua",
      "kotlin",
      "markdown",
      "markdown_inline",
      "nix",
      "python",
      "rasi",
      "regex",
      "requirements", -- pip requirements
      "rust",
      "scss",
      "ssh_config",
      "svelte",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "wgsl",
      "wgsl_bevy",
      "xml",
      "yaml",
    },
  },
  config = function()
    require("nvim-treesitter.install").compilers = { "clang", "gcc" }
  end,
}
