# All comments based on a 7900XTX with mesa 26.1.0

# Vulkan doesn't get used without this
--ignore-gpu-blocklist
# Rasterization is hardware accelerated without this, but not "on all pages" (whatever that means)
--enable-gpu-rasterization
# Tile Update Mode defaults to "One-copy" without this
--enable-zero-copy
# Video Encode isn't hardware accelerated without these
--enable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoEncoder,CanvasOopRasterization,VaapiIgnoreDriverChecks,UseMultiPlaneFormatForHardwareVideo
